### PR TITLE
remove auto-generated files

### PR DESCRIPTION
**Pull request by wchristian**
As discussed in IRC, the *.inc files should not be in the repo in the first places. This commit removes them, puts them in .gitignore and ensures the files are generated when MfPL is being run, thus making it easy to cut releases with the proper files.

This obsoletes PR #12.

### CODE REVIEW

**Comment by devel-chm** [comment]
Thanks for the fix.  I'll make the pull once I figure out how to resolve the conflicts with the current git head.

**Comment by wchristian** [comment]
I rebased it onto master, only needed the newline fixes applied for git to be able to make sense of it.

Note in general: Don't use warn for debug output. Output on stdout, warnings and errors on stderr.

**Comment by devel-chm** [comment]
Thanks.  I'm working on making generate-XS.pl generate the needed files starting with the priority list used by prima, microidium, app-shadertoy, and pdl.  See  the branch chm_generate-XS_work for details including a directory pogl_implemented with lists of the routines implemented in OpenGL and their variations with suffixes.

**Comment by wchristian** [comment]
chm_generate-XS_work looks like you merged after a rebase, which is superfluous and messes up the structure.

image

You'd wanna reset the branch to 1cab71822877b10575f69d0dcf8de09425d4217f and do a force push instead.

**Pull request merged**
